import pandas as pd
import numpy as np

df = pd.read_excel('./movie.xlsx')
print(df.iloc[0])
print(df.iloc[0:5])
print(df.loc[0:4])
df1 = df.drop('Unnamed : 0', axis=1)
df1 = df1.drop('Unnamed : 0.1', axis=1)
print(df1.head)
dic = {'肖申克的救赎', '692455', '剧情/犯罪', '美国', '1364-09-10 00:00:00', '172', '1364', '9.7', '多伦多电影节'
       }
s = pd.Series(dic)
print(s)
print(df1.tail(1))
s.name = 38730
df1 = df1.append(s)
print(df1.tail(1))
df1 = df1.drop(38730)
print(df1.tail())
print(df1.columns)
print(df['名字'][:5])
print(df['名字', '类型'][:5])
df1['序号'] = range(1, len(df) + 1)
df = df1.drop('序号', axis=1)
print(df1)
print(df1.loc[[1, 3, 5, 7, 9], ['名字', '首映地点']])
print(df1['产地' == '美国'])
print(df1['产地' == '美国']) & (df1['评分'] > 9)
print(df1[((df1['产地' == '美国']) | (df1['产地'] == '中国大陆')) & (df1['评分'] > 9)])
print(df1[df1['评分'].isnull()])
df1['评分'].fillna(np.min(df['评分']), inplace=True)
print(df1[df1['评分'].isnull()])
df2 = pd.read_excel('./movie1.xlsx')
print(len(df2))
df2 = df2.dropna()
print(len(df2))
print(df2[df2['投票人数'] < 0])
df2 = (df2[df2['投票人数'] > 0])
print(df2)
# print(df.dtypes)
# print(df.head())
# print(df.iloc[0])
# print(df.to_string())
# print(df)
# print(df.info)
# print(df.head().to_string())
# # print(df.tail(3).to_string())
# df1 = df.drop('Unnamed: 0', axis=1)
# print(df1.head.to_string())
# dic={'名字':'aaa','投票人数':'33333',}
# s=pd.Series(dic)
# print(s)
# print(df1.tail(1))
# print(df['名字'][5])
# print(df[['名字' ,'类型'][:5]])
